title: Jackson Young
logo: assets/img/logo.JPG
description: I combine 5 years of academic physics (particle and space plasma) with 6+ years of business strategy. From working with research professors, post-docs, doctoral candidates to advising C-Suite executives in daily operational business decisions and working directly under directors and VP’s. I have experience ranging from conducting and publishing geophysics research to budgeting multimillion dollar monthly marketing budgets.
show_downloads: true
theme: jekyll-theme-minimal
